### ISSUE TITLE
Make wwwroot the default miglifying directory

### ISSUE THREAD

**Issue by daveabrock** [IEvangelist/IEvangelist.DotNet.Miglifier#3]
This is great! I understand this is only the first iteration but I have a suggestion.

Instead of forcing clients to specify a directory, it might help if clients are only required to specify a directory if it isn't `wwwroot`. Since that is commonly the directory for static files in Core projects, that might be a safe assumption to make. 

Keep up the great work!

**Comment by IEvangelist** [comment]
I like that suggestion and I'll make it part of the next push! Thanks @daveabrock

**Comment by IEvangelist** [comment]
Closing this issue, resolved via: https://github.com/IEvangelist/IEvangelist.DotNet.Miglifier/commit/7bed403da0ddb88fc3cdb0625fe9de68ed9608d2
